---
- name: Check Latest version Node exporter
  shell: |
    curl -s "https://api.github.com/repos/prometheus/node_exporter/releases/latest" | grep -Po '"tag_name": "v\K[0-9.]+' 
  register: node_version
  failed_when: node_version.rc != 0 

- name: Download the node_exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_version.stdout }}/node_exporter-{{ node_version.stdout }}.linux-amd64.tar.gz"  
    dest: /tmp
    mode: '0644'  

- name: Extract the archive
  unarchive:
    src: "/tmp/node_exporter-{{ node_version.stdout }}.linux-amd64.tar.gz"  
    dest: "/tmp"
    remote_src: true

- name: Copy the binaries files to the /usr/local/bin directory and change the ownership. 
  copy:
    src: /tmp/node_exporter-{{ node_version.stdout }}.linux-amd64/node_exporter
    dest: "/usr/local/bin"  
    remote_src: true

- name: Creates node_exporter users
  ansible.builtin.user:
    name: "{{ item }}"
    shell: "/bin/false"
    create_home: false
  with_items:
    - node_exporter

- name:  Set the ownership of the directory
  file:
    path: "/usr/local/bin/node_exporter"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0744'

- name: Template node_exporter.service in the /etc/systemd/system/ directory   
  template:
    src: "{{ role_path }}/templates/node_exporter.service.j2"
    dest: /etc/systemd/system/node_exporter.service
  notify:
  - Reload systemd


- name: Start Node-exporter service
  systemd:
    state: started
    enabled: yes
    name: node_exporter.service