---
- name: Installs and configures Nginx
  block:
   - name: install the nginx
     apt: 
      name: nginx
      state: latest
      update_cache: yes 
   - name: start nginx service
     systemd:
      name: nginx
      state: started
   - name: enable nginx service
     systemd:
      name: nginx
      state: started
      enabled: yes
  become: true
