---

- name: Template create configuration file named prometheus.yml in the /etc/prometheus directory   
  template:
    src: "{{ role_path }}/templates/prometheus.j2"
    dest: /etc/prometheus/prometheus.yml

- name: Copy prometheus.service
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service 
  notify:
  - Reload systemd

- name: Start Prometheus service
  systemd:
    state: started
    enabled: yes
    name: prometheus
