---

- name: Template create configuration file named prometheus.yml in the /etc/prometheus directory   
  template:
    src: "{{ role_path }}/templates/prometheus.j2"
    dest: /etc/prometheus/prometheus.yml

- name: Template create  prometheus.service in the /etc/systemd/system directory   
  template:
    src: "{{ role_path }}/templates/prometheus.service.j2"
    dest: /etc/systemd/system/prometheus.service 
  notify:
  - Reload systemd

- name: Start Prometheus service
  systemd:
    state: started
    enabled: yes
    name: prometheus
