---

- name: Template create configuration file named prometheus.yml in the {{ }} directory   
  template:
    src: "{{ role_path }}/templates/prometheus.j2"
    dest: "{{ prometheus_config_dir }}/prometheus.yml"

- name: Template create  prometheus.service in the /etc/systemd/system directory   
  template:
    src: "{{ role_path }}/templates/prometheus.service.j2"
    dest: /etc/systemd/system/prometheus.service 
  notify:
  - Reload prometheus

- name: Start Prometheus service
  systemd:
    state: started
    enabled: yes
    name: prometheus
